{% set name = "geofileops" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geofileops-{{ version }}.tar.gz
  sha256: 592978155818d3035256c53b80e7dd6b8b8d704f15d8370afd3e1a31e45b6e1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geopandas >=0.10
    - libspatialite >=5.0
    - psutil
    - pygeos
    - pyproj
    - python >=3.8

test:
  imports:
    - geofileops
    - geofileops.util
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geofileops/geofileops
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package to do spatial operations on geo files.
  description: |
    GeofileOps is a library to make spatial operations on geo files fast and 
    easy. Accomplishes this by using geopandas, gdal and ogr2ogr under the hood 
    to perform geospatial operations on files by using all available cores.
  doc_url: https://geofileops.readthedocs.io/
  dev_url: https://github.com/geofileops/geofileops/

extra:
  recipe-maintainers:
    - theroggy
