{% set name = "geofileops" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 488153c3cd1fcd40637dcfec62cddbe0b4f013a880b8c8c377f6e3668a50b429

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - cloudpickle
    - gdal >=3.6.3,<3.10
    - geopandas-base >=0.12,<1
    - libspatialite >=5.0
    - numpy
    - packaging
    - pandas
    - psutil
    - pygeoops >=0.4,<0.5
    - pyogrio >=0.5
    - pyproj
    - shapely >=2,<2.1
    - topojson
    
test:
  imports:
    - geofileops
    - geofileops.util
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
  #commands:
  #  - pip check  # Remove pip check till geopandas 1 is released 
  #requires:
  #  - pip

about:
  home: https://github.com/geofileops/geofileops
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python toolbox to process large vector files faster.
  description: |
    GeofileOps is a python library that makes spatial operations on large vector files
    faster. It accomplishes this by mainly by parallelizing the processing as much as
    possible. Under the hood, it uses gdal, spatialite and geopandas.
  doc_url: https://geofileops.readthedocs.io/
  dev_url: https://github.com/geofileops/geofileops/

extra:
  recipe-maintainers:
    - theroggy
