{% set name = "geofileops" %}
{% set version = "0.10.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f62bdb7e548ef65d3397263cc0f6033fbc10f8b1b1cfc442c5b7fac0286b2b18

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cloudpickle
    - gdal >=3.6.3
    - geopandas-base >=0.12
    - libspatialite >=5.0
    - numpy
    - packaging
    - pandas
    - psutil
    - pygeoops >=0.4
    - pyogrio >=0.7
    - pyproj
    - shapely >=2
    - sqlite >3.40  # >3.40: needed for python 3.11.11

test:
  requires:
    - python {{ python_min }}
  imports:
    - geofileops
    - geofileops.util
  #requires:
  #  - pytest
  #source_files:
  #  - tests
  #commands:
  #  - pytest tests  # Test data files are not included
  #commands:
  #  - pip check  # Remove pip check till geopandas 1 is released 
  #requires:
  #  - pip

about:
  home: https://github.com/geofileops/geofileops
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python toolbox to process large vector files faster.
  description: |
    GeofileOps is a python library that makes spatial operations on large vector files
    faster. It accomplishes this mainly by parallelizing the processing as much as
    possible. Under the hood, it uses gdal, spatialite and geopandas.
  doc_url: https://geofileops.readthedocs.io/
  dev_url: https://github.com/geofileops/geofileops/

extra:
  recipe-maintainers:
    - theroggy
