{% set name = "geofileops" %}
{% set version = "0.2.1a4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geofileops-{{ version }}.tar.gz
  sha256: 7c96352d60f35a0b51ab2d5f8d126258be0583a2a14bee8ef3f31c75badb5e16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geopandas >=0.8.2
    - psutil
    - pygeos
    - pyproj
    - python >=3.8

test:
  imports:
    - geofileops
    - geofileops.util
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/theroggy/geofileops
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package to do spatial operations on geo files.
  description: |
    GeofileOps is a library to make spatial operations on geo files fast and 
    easy. Accomplishes this by using geopandas, gdal and ogr2ogr under the hood 
    to perform geospatial operations on files by using all available cores.
  doc_url: https://geofileops.readthedocs.io/
  dev_url: https://github.com/theroggy/geofileops/

extra:
  recipe-maintainers:
    - theroggy
