{% set name = "geofileops" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geofileops-{{ version }}.tar.gz
  sha256: bc4af2041e25d86a909907e91743cfc29d2ae88eb229a9994339084423812cf5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cloudpickle
    - fiona
    - gdal
    - geopandas >=0.10
    - libspatialite >=5.0
    - numpy
    - pandas
    - psutil
    - pygeos
    - pyproj
    - python >=3.8
    - shapely
    
test:
  imports:
    - geofileops
    - geofileops.util
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geofileops/geofileops
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package to do spatial operations on large geo files.
  description: |
    GeofileOps is a library to make spatial operations on large geo files fast  
    and easy. Accomplishes this by using spatialite, geopandas and gdal under  
    the hood to perform geospatial operations on files by using all available 
    CPU cores.
  doc_url: https://geofileops.readthedocs.io/
  dev_url: https://github.com/geofileops/geofileops/

extra:
  recipe-maintainers:
    - theroggy
