{% set name = "geofileops" %}
{% set version = "0.2.3a1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geofileops-{{ version }}.tar.gz
  sha256: 2ef5422578829203f9dc20ef86e86b9c142e14a288fe9f23f23575b2362f02e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geopandas >=0.8.2
    - psutil
    - pygeos
    - pyproj
    - python >=3.8

test:
  imports:
    - geofileops
    - geofileops.util
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/theroggy/geofileops
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Package to do spatial operations on geo files.
  description: |
    GeofileOps is a library to make spatial operations on geo files fast and 
    easy. Accomplishes this by using geopandas, gdal and ogr2ogr under the hood 
    to perform geospatial operations on files by using all available cores.
  doc_url: https://geofileops.readthedocs.io/
  dev_url: https://github.com/theroggy/geofileops/

extra:
  recipe-maintainers:
    - theroggy
